const actionTypes = {
  CREATE_NEW_ORDER: 'CREATE_NEW_ORDER',
  ERROR: 'ERROR',
  UPDATE_ORDER_DETAIL: 'UPDATE_ORDER_DETAIL',
  UPDATE_SHOW_REPORT: 'UPDATE_SHOW_REPORT',
  CLEAR_REPORT_DATA: 'CLEAR_REPORT_DATA'
}

export {actionTypes}